// Code generated by sqlc. DO NOT EDIT.

package twitter_tweet

import (
	"context"
)

type Querier interface {
	GetTweetByID(ctx context.Context, id int64) (TwitterTweet, error)
	GetTweetsByUserID(ctx context.Context, userID int64) ([]TwitterTweet, error)
}

var _ Querier = (*Queries)(nil)
