// Code generated by sqlc. DO NOT EDIT.

package hdd

import (
	"time"
)

type HDD struct {
	ID        int64
	MakeID    int64
	Name      string
	SizeBytes int64
	Rpm       int64
	CreatedAt time.Time
	UpdatedAt time.Time
}
