version: 2.1
jobs:
  "Go build":
    docker:
      - image: circleci/golang:1.15

    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: go build -v ./...
      - run: go test -v ./...
workflows:
  go:
    jobs:
      - "Go build"
