version: 2.1
jobs:
  "Go build":
    docker:
      - image: circleci/golang:1.15
        environment:
          POSTGRES_HOST: postgresql://test@localhost
      - image: circleci/postgres:11.9-ram
        environment:
          POSTGRES_USER: test
          POSTGRES_DB: testdb
          POSTGRES_HOST_AUTH_METHOD: trust

    working_directory: /go/src/github.com/rickypai/cutie
    steps:
      - checkout
      - run: go build -v ./...
      - run: go build cmd/main.go
      - run: go test -v ./...
      - run: sudo apt-get update
      - run: sudo apt-get install -y postgresql-client
      - run: GO111MODULE=on go get github.com/kyleconroy/sqlc/cmd/sqlc@v1.6.0
      - run: GO111MODULE=on go get github.com/golang/mock/mockgen@v1.4.4
      - run: go get golang.org/x/tools/cmd/gorename
      - run: make test_examples
workflows:
  go:
    jobs:
      - "Go build"
