// Code generated by MockGen. DO NOT EDIT.
// Source: dbmodels/harddrive/querier.go

// Package mock_harddrive is a generated GoMock package.
package mock_harddrive

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	harddrive "github.com/rickypai/cutie/examples/computer_parts/dbmodels/harddrive"
	reflect "reflect"
)

// MockQuerier is a mock of Querier interface
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// GetHDDByID mocks base method
func (m *MockQuerier) GetHDDByID(ctx context.Context, id int64) (harddrive.HDD, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHDDByID", ctx, id)
	ret0, _ := ret[0].(harddrive.HDD)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHDDByID indicates an expected call of GetHDDByID
func (mr *MockQuerierMockRecorder) GetHDDByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHDDByID", reflect.TypeOf((*MockQuerier)(nil).GetHDDByID), ctx, id)
}
