// Code generated by sqlc. DO NOT EDIT.
// source: harddrive.sql

package harddrive

import (
	"context"
)

const getHDDByID = `-- name: GetHDDByID :one
SELECT id, make_id, name, size_bytes, rpm, created_at, updated_at FROM harddrives WHERE id = $1 LIMIT 1
`

func (q *Queries) GetHDDByID(ctx context.Context, id int64) (HDD, error) {
	row := q.db.QueryRowContext(ctx, getHDDByID, id)
	var i HDD
	err := row.Scan(
		&i.ID,
		&i.MakeID,
		&i.Name,
		&i.SizeBytes,
		&i.Rpm,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
