// Code generated by MockGen. DO NOT EDIT.
// Source: dbmodels/twitter_tweet/querier.go

// Package mock_twitter_tweet is a generated GoMock package.
package mock_twitter_tweet

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	twitter_tweet "github.com/rickypai/cutie/examples/twitter/dbmodels/twitter_tweet"
	reflect "reflect"
)

// MockQuerier is a mock of Querier interface
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// GetTweetByID mocks base method
func (m *MockQuerier) GetTweetByID(ctx context.Context, id int64) (twitter_tweet.TwitterTweet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTweetByID", ctx, id)
	ret0, _ := ret[0].(twitter_tweet.TwitterTweet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTweetByID indicates an expected call of GetTweetByID
func (mr *MockQuerierMockRecorder) GetTweetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTweetByID", reflect.TypeOf((*MockQuerier)(nil).GetTweetByID), ctx, id)
}

// GetTweetsByUserID mocks base method
func (m *MockQuerier) GetTweetsByUserID(ctx context.Context, userID int64) ([]twitter_tweet.TwitterTweet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTweetsByUserID", ctx, userID)
	ret0, _ := ret[0].([]twitter_tweet.TwitterTweet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTweetsByUserID indicates an expected call of GetTweetsByUserID
func (mr *MockQuerierMockRecorder) GetTweetsByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTweetsByUserID", reflect.TypeOf((*MockQuerier)(nil).GetTweetsByUserID), ctx, userID)
}
