// Code generated by sqlc. DO NOT EDIT.

package twitter_user

import (
	"context"
)

type Querier interface {
	GetIDByScreenName(ctx context.Context, screenName string) (int64, error)
	GetScreenNameByID(ctx context.Context, id int64) (string, error)
	GetTwitterUserByID(ctx context.Context, id int64) (TwitterUser, error)
	GetTwitterUserByScreenName(ctx context.Context, screenName string) (TwitterUser, error)
}

var _ Querier = (*Queries)(nil)
